services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://user:password@db:5432/my_database

  worker:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - WORKER=1
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://user:password@db:5432/my_database
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - ${REDIS_DIR}:/data
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ${MINIO_DIR}:/data
    command: server /data --console-address ":9001"